../../OracleDBA/test/renameFiles.sh CASTORRECO_Geometry.db metaCASTORRECO.txt CASTORRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh CSCRECODIGI_Geometry.db metaCSCRECODIGI.txt CSCRECODIGI_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh CSCRECO_Geometry.db metaCSCRECO.txt CSCRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh CTRECO_Geometry.db metaCTRECO.txt CTRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh DTRECO_Geometry.db metaDTRECO.txt DTRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh EBRECO_Geometry.db metaEBRECO.txt EBRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh EERECO_Geometry.db metaEERECO.txt EERECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh EPRECO_Geometry.db metaEPRECO.txt EPRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh GeometryFileExtended.db metaGeometryExtended.txt XMLFILE_Geometry_Extended_TagXX
../../OracleDBA/test/renameFiles.sh GeometryFileExtendedGFlash.db metaGeometryExtendedGFlash.txt XMLFILE_Geometry_ExtendedGFlash_TagXX
../../OracleDBA/test/renameFiles.sh GeometryFileIdeal.db metaGeometryIdeal.txt XMLFILE_Geometry_Ideal_TagXX
../../OracleDBA/test/renameFiles.sh GeometryFileIdealGFlash.db metaGeometryIdealGFlash.txt XMLFILE_Geometry_IdealGFlash_TagXX
../../OracleDBA/test/renameFiles.sh HCALRECO_Geometry.db metaHCALRECO.txt HCALRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh RPCRECO_Geometry.db metaRPCRECO.txt RPCRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh TKRECO_Geometry.db metaTKRECO.txt TKRECO_Geometry_TagXX
../../OracleDBA/test/renameFiles.sh ZDCRECO_Geometry.db metaZDCRECO.txt ZDCRECO_Geometry_TagXX
