server.service('Online',           'http://cmsweb.cern.ch/dqm/online')
server.service('Online playback',  'http://cmsweb.cern.ch/dqm/online-playback')
#server.service('Online test',      'http://cmsweb.cern.ch/dqm/online-test')
#server.service('GUI test',         'http://cmsweb.cern.ch/dqm/gui-test')
server.service('CERN Tier-0',      'http://cmsweb.cern.ch/dqm/tier-0')
server.service('CERN Tier-1',      'http://cmsweb.cern.ch/dqm/tier-1')
server.service('CERN RelVal',      'http://cmsweb.cern.ch/dqm/relval')
server.service('CERN CAF',         'http://cmsweb.cern.ch/dqm/caf')
server.service('CERN Development', 'http://cmsweb.cern.ch/dqm/dev')
