#!/bin/sh -ex
SERVER=https://macms01.cern.ch/ap/perfNew-2/slc4_ia32_gcc345
CMSARCH=slc4_ia32_gcc345
RELEASE=CMSSW_3_1_X_2009-06-30-0700

mkdir -p testfiles/$RELEASE
mkdir -p results/$RELEASE
p=results/$RELEASE



files="https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.25.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.50.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.75.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.100.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.125.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.150.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.175.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.200.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/RAW2DIGI-RECO/cpu2/results/$RELEASE/TTbar_IgProf/TTBAR__RAW2DIGI,RECO_IgProfMemTotal.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.25.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.50.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.75.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.100.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.125.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.150.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.175.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.200.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/FASTSIM/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,FASTSIM_IgProfMemTotal.gz \
https://macms01.cern.ch/ap/perfNew-1/$CMSARCH/$RELEASE/perfNew-1/GEN-DIGI2RAW/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__GEN,SIM,DIGI,L1,DIGI2RAW_IgProfMemTotal.gz \
https://macms01.cern.ch/ap/perfNew-2/$CMSARCH/$RELEASE/perfNew-2/HLT/cpu3/results/$RELEASE/TTbar_IgProf/TTBAR__HLT_IgProfMemTotal.gz"

for url in $files
do
  f=`basename $url`
  [ -f testfiles/$RELEASE/$f ] || wget --no-check-certificate -Otestfiles/$RELEASE/$f $url

  eval `scram run -sh`
  scram b clean
  which igprof-analyse

  [ -f $p/$f.MEM_TOTAL.old.txt ] || { igprof-analyse -d -v -r MEM_TOTAL -g testfiles/$RELEASE/$f > $p/$f.MEM_TOTAL.old.txt; }
  [ -f $p/$f.MEM_MAX.old.txt ] || { igprof-analyse -d -v -r MEM_MAX -g testfiles/$RELEASE/$f > $p/$f.MEM_MAX.old.txt; }
  [ -f $p/$f.MEM_LIVE.old.txt ] || { igprof-analyse -d -v -r MEM_LIVE -g testfiles/$RELEASE/$f > $p/$f.MEM_LIVE.old.txt; }

  scram b igprof-analyse
  rm -rf results/$RELEASE/$f.MEM_TOTAL.txt results/$RELEASE/$f.MEM_MAX.txt results/$RELEASE/$f.MEM_LIVE.txt
  which igprof-analyse
  igprof-analyse -d -v -r MEM_TOTAL -g testfiles/$RELEASE/$f > $p/$f.MEM_TOTAL.txt
  igprof-analyse -d -v -r MEM_MAX -g testfiles/$RELEASE/$f > $p/$f.MEM_MAX.txt
  igprof-analyse -d -v -r MEM_LIVE -g testfiles/$RELEASE/$f > $p/$f.MEM_LIVE.txt

  p=results/$RELEASE

  diff -Naur $p/$f.MEM_TOTAL.old.txt $p/$f.MEM_TOTAL.txt 
  diff -Naur $p/$f.MEM_LIVE.old.txt $p/$f.MEM_LIVE.txt
  diff -Naur $p/$f.MEM_MAX.old.txt $p/$f.MEM_MAX.txt
done
